language: C
stage: "Build"
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
env: Everything=awesome

addons:
  apt:
    update: true
    packages:
      - nasm
      - zlib1g-dev
# This code will not work on the MacOS 10.10 image(s). However, since Travis has
# deprecated those images, we are safe to use this method.
  homebrew:
    update: true
    packages:
      - nasm
      - rsync

install: true

script:
  - mkdir _build
  - cd _build
  - cmake -G"Unix Makefiles" ../
  - make -j 4

jobs:
  include:

  #######################################################
  #         macOS and xcode version coverage tests      #
  #######################################################
# Matrix "env:" needs to be overridden so that matrix expansion doesn't result in CC=gcc.

# Matrix hack: Declare same stage multiple times...
    - &macOS_alias
      arch: amd64
      os: osx
      osx_image: xcode7.3
      language: cpp
      compiler: clang
      env: macOS_ver=10.11

    # Subsequent instances use alias to test different versions
    - <<: *macOS_alias
      osx_image: xcode8
      env: macOS_ver=10.11
    - <<: *macOS_alias
      osx_image: xcode8.3
      env: macOS_ver=10.12
    - <<: *macOS_alias
      osx_image: xcode9
      env: macOS_ver=10.12
    - <<: *macOS_alias
      osx_image: xcode9.1
      env: macOS_ver=10.12
    - <<: *macOS_alias
      osx_image: xcode9.2
      env: macOS_ver=10.12
    - <<: *macOS_alias
      osx_image: xcode9.3
      env: macOS_ver=10.13
    - <<: *macOS_alias
      osx_image: xcode9.4
      env: macOS_ver=10.13
    - <<: *macOS_alias
      osx_image: xcode10
      env: macOS_ver=10.13
    - <<: *macOS_alias
      osx_image: xcode10.1
      env: macOS_ver=10.13
    - <<: *macOS_alias
      osx_image: xcode10.2
      env: macOS_ver=10.14
    - <<: *macOS_alias
      osx_image: xcode10.3
      env: macOS_ver=10.14.4
    - <<: *macOS_alias
      osx_image: xcode11
      env: macOS_ver=10.14
    - <<: *macOS_alias
      osx_image: xcode11.1
      env: macOS_ver=10.14
    - <<: *macOS_alias
      osx_image: xcode11.2
      env: macOS_ver=10.14

  #######################################################
  #         Linux version coverage tests           #
  #######################################################

# Matrix hack: Declare same stage multiple times...
    - &trusty_amd64_alias
      arch: amd64
      dist: trusty
      language: C
      compiler: gcc
      env: Ubuntu_ver="Trusty (14.04)"

    # Subsequent instances use alias to test different versions
    - <<: *trusty_amd64_alias
      compiler: clang

# Matrix hack: Declare same stage multiple times...
    - &bionic_amd64_alias
      dist: bionic
      arch: amd64
      language: C
      compiler: gcc
      env: Ubuntu_ver="Bionic (18.04)"

    # Subsequent instances use alias to test different versions
    - <<: *bionic_amd64_alias
      compiler: clang
